# Builds Bill's three frames from art/bill.png (the resting pose, mouth open as drawn)
# and writes them into hooks/bill-art.js as base64 PNGs.
# Run from the repo root after changing the art: python3 art/build.py (needs Pillow)
import base64, io, sys
from PIL import Image, ImageDraw

W, H = 448, 384  # 14 × 6 terminal cells at about 1:2

def blend_fill(px, x0, y0, x1, y1):
    """Repaint a box with skin blended from the rows just above and below it."""
    for x in range(x0, x1 + 1):
        top, bottom = px[x, y0 - 3], px[x, y1 + 3]
        for y in range(y0, y1 + 1):
            t = (y - y0) / max(1, y1 - y0)
            px[x, y] = tuple(round(a + (b - a) * t) for a, b in zip(top, bottom))

def frames(base):
    talk = base.copy()  # the art's own open mouth

    idle = base.copy()
    px = idle.load()
    lip = base.getpixel((488, 205))[:3]
    blend_fill(px, 462, 198, 518, 233)  # cover the open mouth
    d = ImageDraw.Draw(idle)
    d.rectangle([470, 213, 505, 217], fill=lip)  # closed lips
    d.rectangle([505, 210, 513, 214], fill=lip)  # a smug corner

    blink = idle.copy()
    px = blink.load()
    lid = base.getpixel((470, 130))[:3]
    for (x0, x1) in ((443, 461), (513, 533)):
        blend_fill(px, x0, 128, x1, 148)
        ImageDraw.Draw(blink).rectangle([x0 + 1, 138, x1 - 1, 141], fill=lid)
    return {'idle': idle, 'blink': blink, 'talk': talk}

def png(im):
    small = im.resize((W, H), Image.LANCZOS).quantize(colors=128, method=Image.Quantize.FASTOCTREE)
    buf = io.BytesIO(); small.save(buf, 'PNG', optimize=True)
    return buf.getvalue()

if __name__ == '__main__':
    src = sys.argv[1] if len(sys.argv) > 1 else 'art/bill.png'
    dest = sys.argv[2] if len(sys.argv) > 2 else 'hooks/bill-art.js'
    fs = frames(Image.open(src).convert('RGBA'))
    lines = [
        "// Bill's frames as base64 PNGs, for terminals that show images and for the desktop app.",
        '// Generated by art/build.py from art/bill.png; change the art there and run it again.',
        '',
        'export const PNG = {',
    ]
    for name, im in fs.items():
        data = png(im)
        lines.append(f"  {name}: '{base64.b64encode(data).decode()}',")
        print(name, len(data), 'bytes')
        if len(sys.argv) > 3: Image.open(io.BytesIO(data)).save(f'{sys.argv[3]}/frame-{name}.png')
    lines += ['}', '']
    open(dest, 'w').write('\n'.join(lines))
    print('wrote', dest)
